security:
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:


        in_memory:
            memory:
                users:
                    admin: 
                        password: $2y$12$Z5O9BfZo31gw.F7D9T8Le.yNIjEPwVtIzblIh13CV9a177qyCItnq
                        roles:  'ROLE_ADMIN' 

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            provider: in_memory
            form_login:
                check_path: login
                login_path: login
                default_target_path: login
            logout:
                path:   logout
                target: home
            anonymous: ~

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }